### ISSUE TITLE
Breaks with Directus v9.25.0

### ISSUE THREAD

**Issue by berts83231** [ChappIO/directus-extension-prometheus#1]
Logged error

```
[18:36:05.094] WARN: Couldn't register hook "directus-extension-prometheus"
[18:36:05.095] WARN: register is not a function
    err: {
      "type": "TypeError",
      "message": "register is not a function",
      "stack":
          TypeError: register is not a function
              at ExtensionManager.registerHook (file:///directus/node_modules/@directus/api/dist/extensions.js:435:9)
              at ExtensionManager.registerHooks (file:///directus/node_modules/@directus/api/dist/extensions.js:300:22)
              at async ExtensionManager.load (file:///directus/node_modules/@directus/api/dist/extensions.js:183:9)
              at async ExtensionManager.initialize (file:///directus/node_modules/@directus/api/dist/extensions.js:82:13)
              at async createCli (file:///directus/node_modules/@directus/api/dist/cli/index.js:21:5)
    }
```

Likely Cause: https://github.com/directus/directus/pull/18134

Introducing a new directus wrapper package while renaming the old directus package to @directus/api.
This gives us more flexibility in versioning the sub-packages individually, keeping the main version in directus and enables us to adhere to separation of concerns (also making it more obvious that @directus/api contains - you name it - the api).

Solution:

I think bumping the Directus SDK package should fix the issue.

**Comment by ChappIO** [comment]
Thanks for the report. I will take a look at this soon and roll out a new release.

**Comment by ChappIO** [comment]
I created a new release v1.3.0 which is now compatible with 9.26+

Thanks again for the report.
